/**
 * The machine-pulled catalogue, cleaned.
 *
 * These five files are generated — run `npm run ingest` to rebuild them from
 * vendor/catalog-pull-2026-09-13. Do not hand-edit them: the next ingest will
 * overwrite your change, and the thing you wanted to fix almost certainly
 * belongs either in the cleaner (if it is a scrape artefact) or in the curated
 * arrays in items.ts (if it is a judgement call).
 *
 * They are JSON rather than TypeScript on purpose. Ten thousand object
 * literals in a .ts file is real compile cost on every build for no type
 * safety that matters — the shape is asserted once, here, at the boundary.
 */
import type { CatalogItem } from "../../items";

// The `with { type: "json" }` attribute is required by Node's ESM loader, which
// the proof script runs under. Bundlers accept it too, so one spelling works in
// both places.
import adoptMe from "./adopt-me.json" with { type: "json" };
import artManifest from "./art-manifest.json" with { type: "json" };
import sonaria from "./creatures-of-sonaria.json" with { type: "json" };
import fisch from "./fisch.json" with { type: "json" };
import gag2 from "./gag2.json" with { type: "json" };
import ps99 from "./pet-simulator-99.json" with { type: "json" };

/**
 * Every pulled row, in one list.
 *
 * The cast is the single place the generated data meets the type system. It is
 * honest rather than lazy: the ingest script asserts id uniqueness, slug
 * validity and name cleanliness before it writes, and the proof script asserts
 * the same properties again against the assembled catalogue. A structural
 * check here would duplicate both and still not catch the thing that actually
 * goes wrong, which is a row being semantically wrong rather than shaped wrong.
 */
export const PULLED_CATALOG: readonly CatalogItem[] = [
  ...ps99,
  ...adoptMe,
  ...fisch,
  ...sonaria,
  ...gag2,
] as CatalogItem[];

/**
 * Picture files present under public/items, as "<gameSlug>/<filename>".
 *
 * Regenerated by `npm run ingest`. Empty is the normal state — the typographic
 * rarity tile is a real design, not a placeholder waiting to be replaced.
 */
export const ART_MANIFEST: readonly string[] = artManifest;

/** What the pull covers. Games not in here are hand-curated only. */
export const PULLED_GAMES: readonly string[] = [
  "pet-simulator-99",
  "adopt-me",
  "fisch",
  "creatures-of-sonaria",
  "gag2",
];

/** Provenance, shown wherever the size of this catalogue is claimed. */
export const PULL_SOURCES: Record<string, { source: string; pulled: string; caveat?: string }> = {
  "pet-simulator-99": {
    source: "BIG Games official API (ps99.biggamesapi.io)",
    pulled: "13 September 2026",
    caveat:
      "The only one of the five that is a developer-published API rather than a wiki scrape, which is why it is the only game carrying images. 622 pets have no rarity in the API itself; those rows are left unset. BIG Games' terms require written consent before commercial use.",
  },
  "adopt-me": {
    source: "adoptme.fandom.com",
    pulled: "13 September 2026",
    caveat:
      "Potions came back as 2 rows and furniture as 11, which is thinner than the game really has. Potions matter to pricing here — Fly and Ride change what a pet is worth — so treat that category as incomplete.",
  },
  fisch: {
    source: "fisch.fandom.com",
    pulled: "13 September 2026",
    caveat:
      "The 1,426 fish are solid. The cosmetics are not: fischipedia.org blocks automated access, so this came from the thinner legacy Fandom wiki — 96 rod skins against roughly 531 that exist, 17 boats against 312, 81 bobbers against 354. 58% of fish carry no rarity because the wiki never filed them under one.",
  },
  "creatures-of-sonaria": {
    source: "creatures-of-sonaria-official.fandom.com",
    pulled: "13 September 2026",
    caveat:
      "482 creatures against the wiki's own stated 481, so the roster is effectively complete. It carries no materials, palettes or plushies at all — those are hand-curated, and in this game they are the top of the market.",
  },
  gag2: {
    source: "growagarden2.fandom.com + gag2.gg",
    pulled: "13 September 2026",
    caveat:
      "The crop count is 112, not the 33 an earlier hand-built document claimed. 31% of rows carry no rarity.",
  },
};
